import type { ChatPreset } from '../types';

export const DEFAULT_INPUT_PRESET: ChatPreset = {
  id: 'default',
  name: '默认',
  temperature: 1.00,
  frequencyPenalty: 0.00,
  presencePenalty: 0.00,
  repetitionPenalty: 1.00,
  topP: 1.00,
  topK: 40,
  minP: 0,
  topA: 0,
  maxTokens: 18000,
  systemPrompt: '',
  userPrefix: '玩家: ',
  assistantPrefix: '守秘人: ',
  unlockContext: false,
  contextLength: 65536,
  maxResponseTokens: 18000,
  alternativeReplies: 1,
  streamEnabled: false,
  reasoningEffort: 'auto' as const,
  showThoughts: false,
  responseLength: 'auto' as const,
  seed: -1,
  charNameBehavior: 'none' as const,
  continueSuffix: 'none' as const,
  continuePrefill: false,
  assistantPrefill: '',
  mainPrompt: '',
  auxiliaryPrompt: '',
  postHistoryPrompt: '',
  aiAssistPrompt: '根据上文内容，写出{{char}}的下一句对话或行动',
  worldBookTemplate: '[世界书: {0}]',
  scenarioTemplate: '场景: {{scenario}}',
  personalityTemplate: '性格: {{personality}}',
  groupChatPrompt: '请以{{char}}的身份回复。',
  newChatPrompt: '[新的聊天即将开始]',
  newGroupChatPrompt: '[新的群聊即将开始]',
  newExampleChatPrompt: '[新的示例聊天即将开始]',
  continuePrompt: '[继续推进]',
  emptyMessagePrompt: '',
  promptItems: [],
};

export const DEFAULT_EDITOR_PRESET: ChatPreset = {
  id: 'p1',
  name: '空白预设',
  temperature: 1.00,
  frequencyPenalty: 0.00,
  presencePenalty: 0.00,
  repetitionPenalty: 1.00,
  topP: 1.00,
  topK: 40,
  minP: 0,
  topA: 0,
  maxTokens: 4096,
  systemPrompt: '',
  userPrefix: '',
  assistantPrefix: '',
  unlockContext: false,
  contextLength: 65536,
  maxResponseTokens: 4096,
  alternativeReplies: 1,
  streamEnabled: false,
  reasoningEffort: 'auto',
  showThoughts: false,
  responseLength: 'auto',
  seed: -1,
  charNameBehavior: 'none',
  continueSuffix: 'none',
  continuePrefill: false,
  assistantPrefill: '',
  mainPrompt: '',
  auxiliaryPrompt: '',
  postHistoryPrompt: '',
  aiAssistPrompt: '',
  worldBookTemplate: '[世界书: {0}]',
  scenarioTemplate: '场景: {{scenario}}',
  personalityTemplate: '性格: {{personality}}',
  groupChatPrompt: '',
  newChatPrompt: '',
  newGroupChatPrompt: '',
  newExampleChatPrompt: '',
  continuePrompt: '',
  emptyMessagePrompt: '',
  promptItems: [],
  tavernHelperScripts: [],
  regexScripts: [],
};

export const COC_KP_PRESET: ChatPreset = {
  id: 'p2',
  name: '深渊守秘人 - COC 7th',
  temperature: 1.00,
  frequencyPenalty: 0.00,
  presencePenalty: 0.00,
  repetitionPenalty: 1.00,
  topP: 1.00,
  topK: 40,
  minP: 0,
  topA: 0,
  maxTokens: 18000,
  systemPrompt: '你是COC 7版（克苏鲁的呼唤）的守秘人（KP）。你的职责是：\n1. 根据玩家的行动描述推进剧情\n2. 进行检定判定并描述结果\n3. 描绘洛夫克拉夫特式的恐怖氛围\n4. 为玩家提供合理的行动选项\n\n【变量管理】\n你需要在回复末尾使用 JSON Patch 格式管理游戏状态变量。变量采用嵌套路径，例如：\n- 生命值变化：{"op":"replace","path":"/调查员/生命值/当前","value":"8"}\n- 理智值变化：{"op":"delta","path":"/调查员/理智值/当前","value":"-5"}\n- 新增线索：{"op":"insert","path":"/剧情/线索","value":{"名称":"神秘信件","内容":"..."}}\n- 时间推进：{"op":"replace","path":"/世界/时间","value":"深夜"}\n\n请在每次回复中有状态变化时输出变量标签。请始终以叙事者的身份进行回复，保持悬疑和恐怖的氛围。',
  userPrefix: '玩家: ',
  assistantPrefix: '守秘人: ',
  unlockContext: false,
  contextLength: 65536,
  maxResponseTokens: 18000,
  alternativeReplies: 1,
  streamEnabled: false,
  reasoningEffort: 'auto',
  showThoughts: false,
  responseLength: 'auto',
  seed: -1,
  charNameBehavior: 'none',
  continueSuffix: 'none',
  continuePrefill: false,
  assistantPrefill: '',
  mainPrompt: '',
  auxiliaryPrompt: '',
  postHistoryPrompt: '',
  aiAssistPrompt: '根据上文内容，写出{{char}}的下一句对话或行动',
  worldBookTemplate: '[世界书: {0}]',
  scenarioTemplate: '场景: {{scenario}}',
  personalityTemplate: '性格: {{personality}}',
  groupChatPrompt: '请以{{char}}的身份回复。',
  newChatPrompt: '[新的聊天即将开始]',
  newGroupChatPrompt: '[新的群聊即将开始]',
  newExampleChatPrompt: '[新的示例聊天即将开始]',
  continuePrompt: '[继续推进]',
  emptyMessagePrompt: '',
  promptItems: [
    { id: 'main', name: 'Main Prompt', kind: 'marker', role: 'system', trigger: [], position: 'relative', depth: 0, order: 0, content: '', enabled: true },
    { id: 'worldInfoBefore', name: 'World Info (before)', kind: 'marker', role: 'system', trigger: [], position: 'relative', depth: 0, order: 1, content: '', enabled: true },
    { id: 'pi_char_identity', name: '调查员身份定义', kind: 'prompt', role: 'system', trigger: [], position: 'relative', depth: 0, order: 10, content: '你正在主持一场克苏鲁的呼唤(COC)第七版跑团游戏。玩家扮演的调查员是{{char}}。请始终以守秘人(KP)的身份叙述，将调查员视为故事的主角。调查员的行动、对话和决策由玩家控制，你负责描述世界的反应、NPC的行为和事件的发展。不要替调查员做出重大决定或改变其性格。', enabled: true, _library: true },
    { id: 'personaDescription', name: 'Persona Description', kind: 'marker', role: 'system', trigger: [], position: 'relative', depth: 0, order: 20, content: '', enabled: true },
    { id: 'charDescription', name: 'Char Description', kind: 'marker', role: 'system', trigger: [], position: 'relative', depth: 0, order: 21, content: '', enabled: true },
    { id: 'charPersonality', name: 'Char Personality', kind: 'marker', role: 'system', trigger: [], position: 'relative', depth: 0, order: 22, content: '', enabled: true },
    { id: 'scenario', name: 'Scenario', kind: 'marker', role: 'system', trigger: [], position: 'relative', depth: 0, order: 23, content: '', enabled: true },
    { id: 'pi_horror_tone', name: '恐怖氛围强调', kind: 'prompt', role: 'system', trigger: [], position: 'relative', depth: 0, order: 30, content: '【氛围要求】营造洛夫克拉夫特式的宇宙恐怖氛围。恐怖应源自未知与不可名状，而非血腥暴力。通过环境描写(光影、气味、声音、温度)间接暗示危险。描写超自然现象时保持模糊与克制——调查员所感知的只是冰山一角。使用长句叠加制造压迫感，偶尔以短句制造突然的冲击。避免直接展示神话存在的完整形态。', enabled: true, _library: true },
    { id: 'pi_skill_check', name: '检定规则', kind: 'prompt', role: 'system', trigger: [], position: 'relative', depth: 0, order: 40, content: '【检定规则】当调查员的行动结果不确定时，要求进行技能检定。检定结果必须融入叙事描写，不要机械地报告数值。成功时描述调查员的能力如何帮助他克服困难；失败时描述意外的障碍或不利后果；大成功和大失败应有戏剧性的特殊效果。合理判断何时需要检定——日常行为不需要，只有存在风险或不确定性时才要求。', enabled: true, _library: true },
    { id: 'pi_choices', name: '选项多样性', kind: 'prompt', role: 'system', trigger: [], position: 'relative', depth: 0, order: 50, content: '【选项设计】每次回复末尾提供3-5个行动选项。选项应多样化：包含调查类(搜索、询问、观察)、社交类(说服、恐吓、欺骗)、行动类(移动、使用物品、战斗)、以及至少一个出人意料或高风险的选择。涉及技能检定的选项应标注所需技能和难度。不要让所有选项都指向同一个结果——给予玩家真正的选择权。', enabled: true, _library: true },
    { id: 'enhanceDefinitions', name: 'Enhance Definitions', kind: 'marker', role: 'system', trigger: [], position: 'relative', depth: 0, order: 55, content: '', enabled: true },
    { id: 'auxiliary', name: 'Auxiliary Prompt', kind: 'marker', role: 'system', trigger: [], position: 'relative', depth: 0, order: 56, content: '', enabled: true },
    { id: 'worldInfoAfter', name: 'World Info (after)', kind: 'marker', role: 'system', trigger: [], position: 'relative', depth: 0, order: 60, content: '', enabled: true },
    { id: 'pi_roleplay', name: '角色扮演深度', kind: 'prompt', role: 'system', trigger: [], position: 'relative', depth: 0, order: 70, content: '【角色扮演】NPC应有鲜明个性、独特口癖和明确动机。重要NPC应有自己的秘密和议程。对话应反映1920年代的语言风格和社会礼仪。描写NPC时注意微表情、小动作等细节——这些往往暗示着他们没有说出口的事情。调查员的背景故事应适时地融入叙事中，让玩家感到角色与世界的联系。', enabled: true, _library: true },
    { id: 'pi_continuity', name: '场景连贯性', kind: 'prompt', role: 'system', trigger: [], position: 'relative', depth: 0, order: 80, content: '【连贯性】保持场景描写的时间、地点和逻辑连贯。记住之前提到的环境细节、NPC位置和物品状态。天气、光线和时间应随剧情自然推进。调查员获得的线索应在后续剧情中有所呼应。不要突然引入之前没有铺垫的重要元素——神话恐怖应通过逐步积累的不安暗示来揭示。', enabled: true, _library: true },
    { id: 'dialogueExamples', name: 'Chat Examples', kind: 'marker', readOnly: true, role: 'system', trigger: [], position: 'relative', depth: 0, order: 90, content: '', enabled: true },
    { id: 'chatHistory', name: 'Chat History', kind: 'marker', readOnly: true, role: 'system', trigger: [], position: 'relative', depth: 0, order: 100, content: '', enabled: true },
    { id: 'postHistoryInstructions', name: 'Post-History Instructions', kind: 'marker', role: 'system', trigger: [], position: 'relative', depth: 0, order: 110, content: '', enabled: true },
  ],
  tavernHelperScripts: [],
  regexScripts: [],
};

export const DEFAULT_PRESETS: Record<string, ChatPreset> = {
  p1: DEFAULT_EDITOR_PRESET,
  p2: COC_KP_PRESET,
};

export const BUILTIN_PRESET_IDS = new Set(['p1', 'p2']);
