import type { ChatPreset } from '../types';

export const DEFAULT_INPUT_PRESET: ChatPreset = {
  id: 'default',
  name: '默认',
  temperature: 1.00,
  frequencyPenalty: 0.00,
  presencePenalty: 0.00,
  repetitionPenalty: 1.00,
  topP: 1.00,
  topK: 40,
  minP: 0,
  topA: 0,
  maxTokens: 4096,
  systemPrompt: '你是COC 7版（克苏鲁的呼唤）的守秘人（KP）。你的职责是：\n1. 根据玩家的行动描述推进剧情\n2. 进行检定判定并描述结果\n3. 描绘洛夫克拉夫特式的恐怖氛围\n4. 为玩家提供合理的行动选项\n\n【变量管理】\n你需要在回复末尾使用 JSON Patch 格式管理游戏状态变量。变量采用嵌套路径，例如：\n- 生命值变化：{"op":"replace","path":"/调查员/生命值/当前","value":"8"}\n- 理智值变化：{"op":"delta","path":"/调查员/理智值/当前","value":"-5"}\n- 新增线索：{"op":"insert","path":"/剧情/线索","value":{"名称":"神秘信件","内容":"..."}}\n- 时间推进：{"op":"replace","path":"/世界/时间","value":"深夜"}\n\n请在每次回复中有状态变化时输出变量标签。请始终以叙事者的身份进行回复，保持悬疑和恐怖的氛围。',
  userPrefix: '玩家: ',
  assistantPrefix: '守秘人: ',
  unlockContext: false,
  contextLength: 65536,
  maxResponseTokens: 4096,
  alternativeReplies: 1,
  streamEnabled: false,
  reasoningEffort: 'auto' as const,
  showThoughts: false,
  responseLength: 'auto' as const,
  seed: -1,
  charNameBehavior: 'none' as const,
  continueSuffix: 'none' as const,
  continuePrefill: false,
  assistantPrefill: '',
  mainPrompt: '',
  auxiliaryPrompt: '',
  postHistoryPrompt: '',
  aiAssistPrompt: '根据上文内容，写出{{char}}的下一句对话或行动',
  worldBookTemplate: '[世界书: {0}]',
  scenarioTemplate: '场景: {{scenario}}',
  personalityTemplate: '性格: {{personality}}',
  groupChatPrompt: '请以{{char}}的身份回复。',
  newChatPrompt: '[新的聊天即将开始]',
  newGroupChatPrompt: '[新的群聊即将开始]',
  newExampleChatPrompt: '[新的示例聊天即将开始]',
  continuePrompt: '[继续推进]',
  emptyMessagePrompt: '',
  promptItems: [],
};

export const DEFAULT_EDITOR_PRESET: ChatPreset = {
  id: 'p1',
  name: '空白预设',
  temperature: 1.00,
  frequencyPenalty: 0.00,
  presencePenalty: 0.00,
  repetitionPenalty: 1.00,
  topP: 1.00,
  topK: 40,
  minP: 0,
  topA: 0,
  maxTokens: 4096,
  systemPrompt: '',
  userPrefix: '',
  assistantPrefix: '',
  unlockContext: false,
  contextLength: 65536,
  maxResponseTokens: 4096,
  alternativeReplies: 1,
  streamEnabled: false,
  reasoningEffort: 'auto',
  showThoughts: false,
  responseLength: 'auto',
  seed: -1,
  charNameBehavior: 'none',
  continueSuffix: 'none',
  continuePrefill: false,
  assistantPrefill: '',
  mainPrompt: '',
  auxiliaryPrompt: '',
  postHistoryPrompt: '',
  aiAssistPrompt: '',
  worldBookTemplate: '[世界书: {0}]',
  scenarioTemplate: '场景: {{scenario}}',
  personalityTemplate: '性格: {{personality}}',
  groupChatPrompt: '',
  newChatPrompt: '',
  newGroupChatPrompt: '',
  newExampleChatPrompt: '',
  continuePrompt: '',
  emptyMessagePrompt: '',
  promptItems: [],
  tavernHelperScripts: [],
  regexScripts: [],
};

export const COC_KP_PRESET: ChatPreset = {
  id: 'p2',
  name: '深渊守秘人 - COC 7th',
  temperature: 1.00,
  frequencyPenalty: 0.00,
  presencePenalty: 0.00,
  repetitionPenalty: 1.00,
  topP: 1.00,
  topK: 40,
  minP: 0,
  topA: 0,
  maxTokens: 4096,
  systemPrompt: '你是COC 7版（克苏鲁的呼唤）的守秘人（KP）。你的职责是：\n1. 根据玩家的行动描述推进剧情\n2. 进行检定判定并描述结果\n3. 描绘洛夫克拉夫特式的恐怖氛围\n4. 为玩家提供合理的行动选项\n\n【变量管理】\n你需要在回复末尾使用 JSON Patch 格式管理游戏状态变量。变量采用嵌套路径，例如：\n- 生命值变化：{"op":"replace","path":"/调查员/生命值/当前","value":"8"}\n- 理智值变化：{"op":"delta","path":"/调查员/理智值/当前","value":"-5"}\n- 新增线索：{"op":"insert","path":"/剧情/线索","value":{"名称":"神秘信件","内容":"..."}}\n- 时间推进：{"op":"replace","path":"/世界/时间","value":"深夜"}\n\n请在每次回复中有状态变化时输出变量标签。请始终以叙事者的身份进行回复，保持悬疑和恐怖的氛围。',
  userPrefix: '玩家: ',
  assistantPrefix: '守秘人: ',
  unlockContext: false,
  contextLength: 65536,
  maxResponseTokens: 4096,
  alternativeReplies: 1,
  streamEnabled: false,
  reasoningEffort: 'auto',
  showThoughts: false,
  responseLength: 'auto',
  seed: -1,
  charNameBehavior: 'none',
  continueSuffix: 'none',
  continuePrefill: false,
  assistantPrefill: '',
  mainPrompt: '',
  auxiliaryPrompt: '',
  postHistoryPrompt: '',
  aiAssistPrompt: '根据上文内容，写出{{char}}的下一句对话或行动',
  worldBookTemplate: '[世界书: {0}]',
  scenarioTemplate: '场景: {{scenario}}',
  personalityTemplate: '性格: {{personality}}',
  groupChatPrompt: '请以{{char}}的身份回复。',
  newChatPrompt: '[新的聊天即将开始]',
  newGroupChatPrompt: '[新的群聊即将开始]',
  newExampleChatPrompt: '[新的示例聊天即将开始]',
  continuePrompt: '[继续推进]',
  emptyMessagePrompt: '',
  promptItems: [],
  tavernHelperScripts: [],
  regexScripts: [],
};

export const DEFAULT_PRESETS: Record<string, ChatPreset> = {
  p1: DEFAULT_EDITOR_PRESET,
  p2: COC_KP_PRESET,
};

export const BUILTIN_PRESET_IDS = new Set(['p1', 'p2']);
